### ISSUE TITLE
Visibility into memory usage - shuffle vs cache vs user vs jvm overhead

### ISSUE THREAD

**Issue by tenstriker** [hammerlab/spree#61]
Can spree provide this breakdown as a feature? Reason I asked is lot of time spark executor gets killed due to OOM and GC overhead. It's been really hard to monitor what's eating my memory unless I take a full memory dump. I guess dynamic instrumentation per application is what will require to achieve this.

**Comment by ryan-williams** [comment]
Good question. Spree can certainly be made to store and display this info if you can find something in Spark that's exporting it or can be made to export it!

Agreed that this is something that it would be great to have more visibility into as a Spark user, but I think the first step is getting that info out of Spark by some API, any API, first, that Spree can then listen to.

Reopen this if you have a way to get that data!

**Comment by tenstriker** [comment]
thanks @ryan-williams  . I found a spark jira for this. 
https://issues.apache.org/jira/browse/SPARK-9103
https://issues.apache.org/jira/browse/SPARK-8735

I think they may have solved part of it which uses tungston. There's long list comments but it feels its not complete.
