### ISSUE TITLE
Label skipped stages accordingly

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/spree#9]
e.g.:

![](https://s3.amazonaws.com/f.cl.ly/items/0w2Q3O1X3X0Y0r2o1g3i/Screen%20Shot%202015-05-15%20at%208.41.13%20PM.png)

vs:

![](https://s3.amazonaws.com/f.cl.ly/items/2r0L1Q081z390r3y113A/Screen%20Shot%202015-05-15%20at%208.41.59%20PM.png)

Unclear whether I should require that the DB annotate the stages this way or whether I should just figure it out on the frontend…

**Comment by markshervey** [comment]
We just started using Spree and came to this issue as well.  Did you make a decision where it would make more sense to add it?

**Comment by ryan-williams** [comment]
Hey @markshervey, I'm definitely interested in making this work. [`slim` "should" be tagging stages as "skipped"](https://github.com/hammerlab/slim/blob/f13dac769ac17661d854517d2147726f1c4e0f45/server.js#L232), and [Spree "should" be handling/displaying them](https://github.com/hammerlab/spree/blob/802e55492777e58f659363a9db11ce33587245c4/ui/client/widgets/objs-tables/stageTables.html#L19), but I've not specifically tested this flow so I believe that it is not Just Working out of the box at the moment. 

I filed this issue at a much earlier stage in developing Spree (hence the weird green background on the rows in the screenshot above!), haven't had a chance to get back to it, and somewhat hoped that it had been fixed by code I'd added since (including the lines linked to above).

I'm going to do a Spree refresh pretty soon to make it work with the impending Spark 1.5.0 release, so I'll make this a high priority when I have time to look at it. If you're at all interested in contributing, let me know and I can give you additional pointers for doing so.

Out of curiosity, how are skipped stages being displayed to you today?

Finally, I've started a [Spree gitter.im room](https://gitter.im/hammerlab/spree) and will lurk in there for any further questions you might have. Cheers!

**Comment by markshervey** [comment]
Sounds good.  Would love to have a chat about it.  Below is a screenshot, but it doesn't look much different than the one you posted above.  

We considered fixing it hackishly this morning, but once we found the issue we thought we should check in with you to see if we could do something more helpful for the project, so thanks for the quick reply.

![screen shot 2015-08-20 at 17 07 39](https://cloud.githubusercontent.com/assets/6955057/9410776/57154b06-4822-11e5-8397-7c991f45693f.png)

**Comment by ryan-williams** [comment]
Cool, well drop into [the Gitter room](https://gitter.im/hammerlab/spree) anytime and I'll likely be there.

I'm confused about your screenshot; should any of those stages be shown as "skipped"? It looks like they were all run to completion or are active.

**Comment by ryan-williams** [comment]
So, I happened to run into this today and have done some debugging.

Turns out I am (correctly, I think) [setting `status: SKIPPED` on the `Stage` records](https://github.com/hammerlab/slim/blob/02785ca2f7016fe3eb4734e4826cb5e8cf8ac79f/server.js#L225-L234), but am not 1) writing them to the corresponding `StageAttempt` records, or 2) otherwise propagating the `Stage`-level skipped-ness to the `StageAttempt`s that are displayed in Spree, e.g. in your screenshot of the /stages page above.

Hopefully I can have a fix shortly.

**Comment by ryan-williams** [comment]
progress..

![](http://cl.ly/image/0L3Z0i0i0b1c/Screen%20Shot%202015-08-22%20at%204.51.01%20PM.png)

![](http://cl.ly/image/2T153Z3K3e0K/Screen%20Shot%202015-08-22%20at%204.51.37%20PM.png)

**Comment by ryan-williams** [comment]
@markshervey this should be fixed; use the latest `slim` (1.1.6; which HEAD here now points to) and HEAD (f5c74fc) here and let me know how it goes!

**Comment by markshervey** [comment]
Just updated and it all looks good!  Thanks for the quick turnaround!
